@host = http://127.0.0.1:6000/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Token verification
GET {{host}}/verify-token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzMDEzMzU3fQ.NVs-91y8TdtsQqGGK8-ktDct20I6EbI_c7J-PRXmuLg HTTP/1.1

